---
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Welcome!

Welcome to the Atlanta R Users Group site, where we will maintain an archive of presentations given at our monthly users group meetings. 

## 24 June 2021 Meeting

Please mark your calendar for June 24th from 7:30P - 8:30P ET for our next meeting, where we will share two presentations, including:

* The Patchwork package: reproducible composites of ggplot2 objects, by [Melinda Higgins, Ph.D.](http://bit.ly/3eYC7XL)
* Animated charts with R, by Sridhar Sitharaman 

Register at [Meetup.com](https://bit.ly/3q0EYTB) to receive the videoconference information for the meeting. 

## Presentation Archive

|Date|Presenter|Presentation|
|:---------|:---|:---- |
|29 April 2021|[Warren Hearnes, Ph.D.](https://bit.ly/3zor6Xs)|Building Applications with Shiny|
|25 March 2021|[Melinda Higgins, Ph.D.](http://bit.ly/3eYC7XL)|[Reproducibility with the Rmarkdown / Knitr Ecosystem](https://bit.ly/3cmtWmo)|
|25 March 2021|[Len Greski](https://bit.ly/3kPEgpf)|[Debugging R Code: Monte Carlo Simulations of Bernoulli Trials](https://bit.ly/3damdqV)<br>[R code](https://bit.ly/3feEEgO)|
|25 February 2021|Rob Gordon|[An Introduction to Web Scraping in R](http://bit.ly/3qWogUR)<br><br> [Github site](http://bit.ly/3uJ3x9E)|
|25 February 2021|John Hackett|[RODBC](http://bit.ly/3dMPppD)|
|28 January 2021|[Len Greski](https://bit.ly/3kPEgpf)|[Reading Fixed Files in R](https://bit.ly/2ZgadgR)|
|21 December 2020| Steve Pittard|[Predictive Modeling](http://bit.ly/3qp2IA7)|







